### ISSUE TITLE
Additional properties added to my json

### ISSUE THREAD

**Issue by russormes** [FauxFaux/ansible-ghetto-json#4]
Thanks for the module, exactly what we were looking for. I am surprised this had not been pulled into the ansible modules bank. 

All work well, except for this: 
 
 "_ansible_check_mode": "False",
  "_ansible_debug": "False",
  "_ansible_diff": "False",
  "_ansible_module_name": "ghetto_json",
  "_ansible_no_log": "False",
  "_ansible_selinux_special_fs": "[u'fuse', u'nfs', u'vboxsf', u'ramfs', u'9p']",
  "_ansible_socket": "None",
  "_ansible_syslog_facility": "LOG_USER",
  "_ansible_verbosity": 0,
  "_ansible_version": "2.3.0.0",

This was added to the top of my json file. Any idea why or how to turn it off?

**Comment by cggaldes** [comment]
+1

**Comment by russormes** [comment]
So the additional properties are because ansible adds those as parameters to the module call and the ghetto_json script adds all parameters to the json document. 

As the paths into the document I wanted to use were actually dynamic, using ansible variables, I was passing the parameters as a dictionary variable and getting a deprecation warning from the ansible engine, so I adjusted the script to accept a single parameter, `conf_dic` which is a dictionary of the paths and 'targets' and then just use that one parameter to adjust the json document. 

```python
import ast

def main(params_list):
    main_params = dict(x.split("=", 2) for x in params_list)

    config = main_params.pop('conf_dic')
    params = ast.literal_eval(config)
    path = params.pop('path')
    changed = False
```
This, of course, also had the effect of removing the ansible parameters. Sorry this is not a general solution!
